### ISSUE TITLE
Use one backbone with different heads

### ISSUE THREAD

**Issue by brunopatricio2012** [archinetai/surgeon-pytorch#2]
Is it possible to save the results from the backbone and apply them on the heads of the all the other models. My goal was to try to save time by avoiding repeating the backbone part. Instead of running the 3 complete models (left), only run the backbone 1 time and switch only the heads for the 3 models (right), therefore not repeating executing the backbone every time in yolov5 model.

Thank you for the help!

**Comment by flavioschneider** [comment]
Yes, as long as the computational graph is not dynamic, you can extract parts of the model using `Extract`. 

You would have to extract two different versions of the model. The first for the backbone, where the `node_out` are the embedding you want to save. The second for the repeated part, where you would have to provide `node_in` in the model graph where the embeddings are connected.  See the README for a concrete example. 

If you are using Huggingface you have to use their own tracer and fix parameters that make the graph static. Here's an example: 

```python 
from transformers import BertForSequenceClassification
from transformers.utils.fx import HFTracer
import inspect

model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=3)

# Pick dynamic input 
input_names = ['input_ids']

# Fix args that make graph dynamic 
sig = inspect.signature(model.forward)
concrete_args = {p.name: p.default for p in sig.parameters.values() if p.name not in input_names}

# Get nodes with custom tracer and fixed args
print(get_nodes(model, tracer = HFTracer, concrete_args = concrete_args)) 

# Extract model with custom tracer and fixed args 
model_ext = Extract(
    model, 
    node_in = { 'bert.embeddings.dropout': 'embeddings' }, 
    node_out = 'bert.pooler.activation', 
    tracer = HFTracer, 
    concrete_args = concrete_args
)
```

**Comment by brunopatricio2012** [comment]
![Capturar](https://user-images.githubusercontent.com/24433634/174081605-57324704-5d8b-4c72-9a76-46603594e4f6.PNG)

I forgot to post the diagram, so here it is and I want to know if the code that you sent me can provide something like the diagram?

Thanks for your help!

**Comment by flavioschneider** [comment]
Yes.

**Comment by diogompontes** [comment]
Hello @flavioschneider .
I'm having the same problem as @brunopatricio2012 but in my case is with model Yolov5s. I can't addapt my code with the solution that you provided.
Is that possible you get some help for my problem?

Thanks a lot!
